# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

# [plugins.zsh-autocomplete]
# github = "marlonrichert/zsh-autocomplete"
# apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zoxide]
github = "ajeetdsouza/zoxide"
apply = ["defer"]

# [plugins.edit-command-line]
# inline = '''
# zsh-defer autoload -Uz edit-command-line
# zsh-defer zle -N edit-command-line
# zsh-defer bindkey "^[" edit-command-line
# '''

[plugins.kubectl]
inline = '''
zsh-defer autoload -Uz compinit
zsh-defer compinit
zsh-defer source <(kubectl completion zsh)
'''

